2023 import
Frc5572/FRC2022 pull request #205
Opened 2023-01-13 03:23 UTC by agrinmanriv0537

Applying 2023 dependency changes to 2022 code, everything functional.

2023-01-13 13:35 UTC, legoguy1000 requested changes

2023-01-13 13:35 UTC, legoguy1000 commented on .vscode/extensions.json
> -}
don't delete

2023-01-13 13:35 UTC, legoguy1000 commented on .vscode/settings.json
> -  "terminal.integrated.defaultProfile.windows": "Git Bash"
don't delete.  THis is just from the import.

2023-01-13 13:35 UTC, legoguy1000 commented on src/main/java/frc/lib/InfiniteCommand.java
> +// package frc.lib;
If we're not using this, just delete it.

2023-01-13 13:35 UTC, legoguy1000 commented on src/main/java/frc/robot/autos/P1_3B.java
> +                //     this.intake).withTimeout(1.5));
uncomment this so its back to what it was.

2023-01-13 13:35 UTC, legoguy1000 commented on src/main/java/frc/robot/autos/P1_3B.java
> +                    initialState.holonomicRotation))), part1, part2,
put this back to what it was

2023-01-13 13:35 UTC, legoguy1000 commented on src/main/java/frc/robot/modules/swervedrive/SwerveModule.java
> +
delete

2023-01-13 13:35 UTC, legoguy1000 commented on src/main/java/frc/robot/modules/swervedrive/SwerveModule.java
> +        // return new SwerveModulePosition(.5, new Rotation2d(.5));
delete

2023-01-16 21:52 UTC, gvaldez7206 approved these changes, later dismissed
Looks good

2023-01-16 21:55 UTC, gvaldez7206 approved these changes
Looks good

2023-01-16 21:56 UTC, legoguy1000 approved these changes

2023-01-16 21:56 UTC, merged